[package]
name = "tensor-derive-new-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tensor-traits = { path = "../tensor-traits"}
tensor-derive-new = { path = "../tensor-derive-new"}


