[package]
name = "tensor-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = "*"
quote = "*"
num-traits = "*"
tensor-traits = { path = "../tensor-traits"}

