[package]
name = "tensor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "*"
# num-complex = "*"
tensor-derive = { path = "tensor-derive"}
tensor-traits = { path = "tensor-traits"}
